### ISSUE TITLE
[G2NoTR, Union 1.0k] Error after launching the game (in the main menu) 

### ISSUE THREAD

**Issue by Fabiosek** [Gratt-5r2/zTrollStoneThrowing#1]
**Error after launching the game (in the main menu):** 
![obraz](https://user-images.githubusercontent.com/9134375/132241920-8508d2ac-710e-4ec7-ac87-aded0f5e9f09.png)

**Version:** 
![obraz](https://user-images.githubusercontent.com/9134375/132242076-694f4335-7185-49a3-a14d-bd4da9a687d3.png)

**Comment by Gratt-5r2** [comment]
> **Error after launching the game (in the main menu):**

Check it now, I added the newest zParserExtender. It should help.

**Comment by Fabiosek** [comment]
> 
> 
> > **Error after launching the game (in the main menu):**
> 
> Check it now, I added the newest zParserExtender. It should help.

Now works, but displays strange elements (without marvin mode):

![obraz](https://user-images.githubusercontent.com/9134375/132360588-28d2e8bc-6014-4412-83db-e5812dfa4fd8.png)

PS. In my opinion, the stone should appear earlier, for example at this point (in this frame): 

![obraz](https://user-images.githubusercontent.com/9134375/132360931-5f31f50b-b79f-4f53-b3e2-fab1c927767d.png)
